# Generated by Django 4.0.3 on 2022-04-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
