# Generated by Django 4.0.3 on 2022-05-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_user_alter_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tages',
            field=models.ManyToManyField(related_name='posts', to='posts.tag'),
        ),
    ]
