# Generated by Django 4.0.3 on 2022-05-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_tages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tages',
        ),
    ]
