# Generated by Django 4.0.3 on 2022-05-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_tages'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tages',
            field=models.ManyToManyField(related_name='posts', to='posts.tag'),
        ),
    ]
