# Generated by Django 4.0.3 on 2022-05-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tages',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
