# Generated by Django 4.0.4 on 2022-05-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_rename_user_user_username_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
